print("😀 Grinning Face")
print("😂 Laughing Face")
print("😍 Heart Eyes")
print("😎 Cool Face")
print("🥺 Pleading Face")
print("❤️ Red Heart")
print("👍 Thumbs Up")
print("🎉 Party Popper")
print("🔥 Fire")
print("✨ Sparkles")